trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml
    - .travis.yml

pr:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - .appveyor.yml
    - .travis.yml

jobs:
- job:
  pool:
    vmImage: windows-latest
  strategy:
    matrix:
      Release:
        configuration: Release
      Debug:
        configuration: Debug

  steps:
  - script: |
      git submodule update --init --recursive
      mkdir build
      cd build
      cmake .. -G "Visual Studio 16 2019" -A Win32
    displayName: 'Before build'

  - script: |
      cd build
      cmake --build . --config %configuration%
    displayName: 'Build'

  - script: |
      cd "build\bin\%configuration%"
      7z a "..\..\..\%configuration%.zip" ..\..\..\COPYING ..\..\..\README.md Cxbx.exe glew32.dll subhook.dll CxbxVSBC.dll cxbxr-debugger.exe capstone.dll cs_x86.dll
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    displayName: 'After build'

  - publish: $(configuration).zip
    artifact: $(configuration)
    condition: and(succeeded(), eq(variables['Agent.JobName'], 'Release'))
    displayName: Publish artifact(s)
