# Documentation is here: https://www.appveyor.com/docs/appveyor-yml/

init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_repo_commit"

image:
  # If this is modified, please also update the build script
  - Visual Studio 2019

configuration:
  # The builds will be run in this order
  - Release
  - Debug

clone_depth: 1

before_build:
  - cmd: |-
      git submodule update --init --recursive
      mkdir build
      cd build
      cmake .. -G "Visual Studio 16 2019" -A Win32

build_script:
  - cmd: cmake --build . --config %CONFIGURATION%

after_build:
  - cmd: |-
      cd bin\%CONFIGURATION%
      7z u %APPVEYOR_BUILD_FOLDER%\export\%CONFIGURATION%.zip ..\..\..\COPYING ..\..\..\README.md
      7z u %APPVEYOR_BUILD_FOLDER%\export\%CONFIGURATION%.zip Cxbx.exe glew32.dll subhook.dll CxbxVSBC.dll
      7z u %APPVEYOR_BUILD_FOLDER%\export\%CONFIGURATION%.zip cxbxr-debugger.exe capstone.dll cs_x86.dll

artifacts:
  - path: export/*.zip

