# Documentation is here: https://www.appveyor.com/docs/appveyor-yml/

init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_repo_commit"

branches:
  only:
    - master

image: 
  - Visual Studio 2017

configuration:
  # The builds are run in this order
  # Each configuration will compile all below platforms
  - Release
  - Debug

platform:
  # Build the debugger and managed deps
  # This must be done first!
  - Any CPU
  # Build native binaries
  - Win32

build:
  project: build/win32/Cxbx.sln
  parallel: true
  verbosity: minimal

before_package:
  # Pass in the build configuration
  - cmd: GatherArtifacts.bat %CONFIGURATION%

artifacts:
  - path: export/*.zip

install:
  # Git clone happens between init and install
  - cmd: git submodule update --init --recursive
