init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_repo_commit"
branches:
  only:
  - master
image: 
- Visual Studio 2017  
configuration:
- Release
- Debug
platform:
  - Any CPU
  - Win32
build:
  project: build/win32/Cxbx.sln
  parallel: true
  verbosity: minimal
after_build:
  - cmd: PackageBuild.bat %CONFIGURATION%
artifacts:
- path: export/*.zip
install:
  # Git clone happens between init and install 
  - cmd: git submodule update --init --recursive
